### ISSUE TITLE
Error 500 - URL was not normalized

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/docker#163]
Hi,

I had compose georchestra stable branch (22.0), all modules seems works except the console.

I am redirect to weird URL : 

https://georchestra-127-0-1-1.traefik.me/console/manager////////////////////

And i get 500 error :

```
HTTP ERROR 500 org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
URI:	/console/manager////////////////////
STATUS:	500
MESSAGE:	org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
SERVLET:	proxy
CAUSED BY:	org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
Caused by:

org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:248)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:193)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Images

![image](https://user-images.githubusercontent.com/16317988/218676924-2d4ed27f-1716-41bc-b9d0-08a1628daa7d.png)

### containers

![image](https://user-images.githubusercontent.com/16317988/218677002-9f77dfca-0246-460c-8e12-1099b11a152c.png)

## Steps

1. clone --recursive

2. Remove some useless modules (e.g geonetwork) from docker-compose files

3. Run

`docker compose up -d`

4. Swirch to stable branch
`git checkout 22.0 && git submodule update`

5. Clean images and container

```
docker rmi $(docker images -q)
docker rm -f $(docker ps -a -q)
```

6.  Run

`docker compose up -d`

7. Try to access to console from header

**Comment by Gaetanbrl** [comment]
ref https://github.com/georchestra/docker/pull/164

**Comment by arnaud-morvan** [comment]
@Gaetanbrl 

Sorry, forgot to say that bad redirections returned 301 permanent redirect, I fixed them and moved to 302 temporary redirect.

You may need to clear cache in browser.

In chromium I gone in developer tools, tab Application / Cache / Cache Storage and deleted the only one entry there.

After that it was working.

**Comment by Gaetanbrl** [comment]
ya @arnaud-morvan , before lunch i'd clear browser data before clean & install container + images and all works fine now with master branch.

Thanks  i close.
