### ISSUE TITLE
Container docker_datafeeder is not starting due to mail problems

### ISSUE THREAD

**Issue by superbully** [georchestra/docker#308]
Hi, the datafeeder container does not up because the mail service is not configured. I don´t know where to configure it to disable it. I would be very grateful if someone knows where I can disable it.
Thank you very much in advance.

```
datafeeder_1                 | 2024-10-31 10:45:16.029  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Mail server is not available
datafeeder_1                 | 2024-10-31 10:45:16.060 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
datafeeder_1                 |
datafeeder_1                 | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Mail server is not available
datafeeder_1                 |  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  at org.georchestra.datafeeder.app.DataFeederApplication.main(DataFeederApplication.java:27) ~[classes!/:na]
datafeeder_1                 |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
datafeeder_1                 |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
datafeeder_1                 |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
datafeeder_1                 |  at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
datafeeder_1                 |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[datafeeder.jar:na]
datafeeder_1                 |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[datafeeder.jar:na]
datafeeder_1                 |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[datafeeder.jar:na]
datafeeder_1                 |  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[datafeeder.jar:na]
datafeeder_1                 | Caused by: java.lang.IllegalStateException: Mail server is not available
datafeeder_1                 |  at org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration.validateConnection(MailSenderValidatorAutoConfiguration.java:55) ~[spring-boot-autoconfigure-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
datafeeder_1                 |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
datafeeder_1                 |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
datafeeder_1                 |  at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
datafeeder_1                 |  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  ... 27 common frames omitted
datafeeder_1                 | Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp, 25; timeout -1
datafeeder_1                 |  at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2210) ~[jakarta.mail-1.6.5.jar!/:1.6.5]
datafeeder_1                 |  at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722) ~[jakarta.mail-1.6.5.jar!/:1.6.5]
datafeeder_1                 |  at javax.mail.Service.connect(Service.java:342) ~[jakarta.mail-1.6.5.jar!/:1.6.5]
datafeeder_1                 |  at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518) ~[spring-context-support-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.mail.javamail.JavaMailSenderImpl.testConnection(JavaMailSenderImpl.java:398) ~[spring-context-support-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
datafeeder_1                 |  at org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration.validateConnection(MailSenderValidatorAutoConfiguration.java:52) ~[spring-boot-autoconfigure-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
datafeeder_1                 |  ... 34 common frames omitted
datafeeder_1                 | Caused by: java.net.UnknownHostException: smtp
datafeeder_1                 |  at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:na]
datafeeder_1                 |  at java.base/java.net.SocksSocketImpl.connect(Unknown Source) ~[na:na]
datafeeder_1                 |  at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
datafeeder_1                 |  at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
datafeeder_1                 |  at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:335) ~[jakarta.mail-1.6.5.jar!/:1.6.5]
datafeeder_1                 |  at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214) ~[jakarta.mail-1.6.5.jar!/:1.6.5]
datafeeder_1                 |  at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160) ~[jakarta.mail-1.6.5.jar!/:1.6.5]
datafeeder_1                 |  ... 39 common frames omitted
datafeeder_1                 |
docker_datafeeder_1 exited with code 1
import_1                     | 127.0.0.1 - - [31/Oct/2024:10:45:17 +0000] "GET / HTTP/1.1" 200 4516 "-" "Wget" "-"
datahub_1                    | 127.0.0.1 - - [31/Oct/2024:10:45:17 +0000] "GET /datahub/ HTTP/1.1" 200 19223 "-" "curl/8.5.0" "-"
datafeeder_1                 | 2024-10-31 10:45:18.401  INFO 1 --- [           main] o.g.d.app.DataFeederApplication          : Starting DataFeederApplication on 0598c3438f3a with PID 1 (/opt/app/datafeeder.jar started by geo in /)
datafeeder_1                 | 2024-10-31 10:45:18.404  INFO 1 --- [           main] o.g.d.app.DataFeederApplication          : The following profiles are active: georchestra
geoserver_1                  | 31 Oct 10:45:19 IN
```

**Comment by fvanderbiest** [comment]
I think datafeeder requires the smtp service - there's currently no way to disable emails.
