### ISSUE TITLE
Could not access file "$libdir/postgis-2.3"

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/docker#8]
```
database_1                  | ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory
database_1                  | STATEMENT:  select PostGIS_Lib_Version()
geonetwork_1                | 2017-10-30 16:01:55,506 ERROR [jeeves.engine] - Raised exception while starting the application. Fix the error and restart.
geonetwork_1                | 2017-10-30 16:01:55,506 ERROR [jeeves.engine] -    Handler   : org.fao.geonet.Geonetwork
geonetwork_1                | 2017-10-30 16:01:55,506 ERROR [jeeves.engine] -    Exception : java.lang.RuntimeException: java.io.IOException: Error occurred creating table
geonetwork_1                | 2017-10-30 16:01:55,506 ERROR [jeeves.engine] -    Message   : java.io.IOException: Error occurred creating table
geonetwork_1                | 2017-10-30 16:01:55,507 ERROR [jeeves.engine] -    Stack     : java.lang.RuntimeException: java.io.IOException: Error occurred creating table
geonetwork_1                | 	at org.fao.geonet.kernel.search.SearchManager$Spatial.createWriter(SearchManager.java:1754)
geonetwork_1                | 	at org.fao.geonet.kernel.search.SearchManager$Spatial.<init>(SearchManager.java:1726)
geonetwork_1                | 	at org.fao.geonet.kernel.search.SearchManager.initNonStaticData(SearchManager.java:541)
geonetwork_1                | 	at org.fao.geonet.kernel.search.SearchManager.init(SearchManager.java:521)
geonetwork_1                | 	at org.fao.geonet.Geonetwork.start(Geonetwork.java:319)
geonetwork_1                | 	at jeeves.server.JeevesEngine.initAppHandler(JeevesEngine.java:454)
geonetwork_1                | 	at jeeves.server.JeevesEngine.init(JeevesEngine.java:175)
geonetwork_1                | 	at jeeves.server.sources.http.JeevesServlet.init(JeevesServlet.java:82)
geonetwork_1                | 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
geonetwork_1                | 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
geonetwork_1                | 	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:422)
geonetwork_1                | 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:892)
geonetwork_1                | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
geonetwork_1                | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
geonetwork_1                | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
geonetwork_1                | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
geonetwork_1                | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
geonetwork_1                | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
geonetwork_1                | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geonetwork_1                | 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
geonetwork_1                | 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
geonetwork_1                | 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
geonetwork_1                | 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
geonetwork_1                | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
geonetwork_1                | 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:437)
geonetwork_1                | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
geonetwork_1                | 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
geonetwork_1                | 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
geonetwork_1                | 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
geonetwork_1                | 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
geonetwork_1                | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geonetwork_1                | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
geonetwork_1                | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geonetwork_1                | 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
geonetwork_1                | 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
geonetwork_1                | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geonetwork_1                | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
geonetwork_1                | 	at org.eclipse.jetty.server.Server.start(Server.java:422)
geonetwork_1                | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
geonetwork_1                | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
geonetwork_1                | 	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
geonetwork_1                | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geonetwork_1                | 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1540)
geonetwork_1                | 	at java.security.AccessController.doPrivileged(Native Method)
geonetwork_1                | 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1462)
geonetwork_1                | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
geonetwork_1                | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
geonetwork_1                | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
geonetwork_1                | 	at java.lang.reflect.Method.invoke(Method.java:498)
geonetwork_1                | 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:215)
geonetwork_1                | 	at org.eclipse.jetty.start.Main.start(Main.java:458)
geonetwork_1                | 	at org.eclipse.jetty.start.Main.main(Main.java:76)
geonetwork_1                | Caused by: java.io.IOException: Error occurred creating table
geonetwork_1                | 	at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:688)
geonetwork_1                | 	at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:140)
geonetwork_1                | 	at org.fao.geonet.kernel.search.spatial.SpatialIndexWriter.attemptToCreateSpatialIndexFeatureStore(SpatialIndexWriter.java:493)
geonetwork_1                | 	at org.fao.geonet.kernel.search.spatial.SpatialIndexWriter.findSpatialIndexStore(SpatialIndexWriter.java:480)
geonetwork_1                | 	at org.fao.geonet.kernel.search.spatial.SpatialIndexWriter.createFeatureStore(SpatialIndexWriter.java:453)
geonetwork_1                | 	at org.fao.geonet.kernel.search.spatial.SpatialIndexWriter.<init>(SpatialIndexWriter.java:131)
geonetwork_1                | 	at org.fao.geonet.kernel.search.SearchManager$Spatial.createWriter(SearchManager.java:1748)
geonetwork_1                | 	... 51 more
geonetwork_1                | Caused by: org.postgresql.util.PSQLException: ERROR: could not access file "$libdir/postgis-2.3": No such file or directory
geonetwork_1                | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
geonetwork_1                | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
geonetwork_1                | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
geonetwork_1                | 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
geonetwork_1                | 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
geonetwork_1                | 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:254)
geonetwork_1                | 	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
geonetwork_1                | 	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
geonetwork_1                | 	at org.geotools.data.postgis.PostGISDialect.getVersion(PostGISDialect.java:896)
geonetwork_1                | 	at org.geotools.data.postgis.PostGISDialect.postCreateTable(PostGISDialect.java:687)
geonetwork_1                | 	at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:685)
geonetwork_1                | 	... 57 more
geonetwork_1                | 
```

**Comment by pmauduit** [comment]
> database_1                  | ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory

That is pretty weird: who is responsible of installing the PostGIS extension on the database ? If `CREATE EXTENSION postgis ;` occured before and everything is saved in a volume, it is likely that plugging a newer docker image onto a previous volume will cause this kind of issue (version mismatch between an old db and more recent postgis binaries). That said, you seem to have the opposite issue (a more recent db than the postgres/postgis container you are using).
